# Generated by Django 6.0 on 2025-12-20 04:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postviaje',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AlterField(
            model_name='postviaje',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
